apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx
spec:
  selector:
    matchLabels:
      app: mynginx
  replicas: 5
  template:
    metadata:
      labels:
        app: mynginx
        version: v1.0.0
    spec:
      containers:
      - name: szamandevexecpl-nginx
        image: szamandevexecpl/nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mynginx
spec:
  selector:
    app: mynginx
  ports:
  - port: 5432
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx
  labels:
    name: mynginx
spec:
  rules:
  - host: "localhost"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: mynginx
            port: 
              number: 5432
