name: Deploy to PROD

on:
  push:
    tags:
    - "*"

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to PROD
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script_stop: true
          script: |
            git clone https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/pythonids/py_many-species.git py_many_species_${{ github.ref_name }}

      - name: install app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd py_many_species_${{ github.ref_name }}
            ls -la
            npm --version
            # npm install .

      - name: del and start app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd py_many_species_${{ github.ref_name }}
            # pm2 delete myApp
            # pm2 start npm --name "myApp" -- run "start:production"
            pm2 status
